_BASE_: "../Base-HOIRCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./output/model_final_280758.pkl"
  HOI_ON: True
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
ZERO_SHOT:
  ZERO_SHOT_ON: True
  PRECOMPUTED_SEMANTIC_EMBEDDINGS: "./datasets/precomputed_semantic_embeddings.pkl"
  NOVEL_CLASSES: []
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (40000, 80000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 1000
DATASETS:
  TRAIN: ("hico-det_train", )
  TEST: ("hico-det_test", )